knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/xvfb-run  /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/xvfb-run -a -s "-screen 0 640x480x16" /usr/bin/wkhtmltoimage
        options:    []

    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 3600 # In seconds