<?php

namespace App\Repository;

/**
 * OrientationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

class OrientationRepository extends \Doctrine\ORM\EntityRepository
{


    public function getchoixFiliere($annee) {

        $query="SELECT '1' as num, choix1 as choix, count(choix1) as c FROM ChoixOrientation WHERE anneeuniv = '".$annee."' GROUP BY choix1
	            UNION
	            SELECT '2' as num, choix2 as choix, count(choix2) as c FROM ChoixOrientation WHERE anneeuniv = '".$annee."' GROUP BY choix2
	            UNION
	            SELECT '3' as num, choix3 as choix, count(choix3) as c FROM ChoixOrientation WHERE anneeuniv = '".$annee."' GROUP BY choix3
	            UNION
	            SELECT '4' as num, choix4 as choix, count(choix4) as c FROM ChoixOrientation WHERE anneeuniv = '".$annee."' GROUP BY choix4
	            UNION
	            SELECT '5' as num, choix5 as choix, count(choix5) as c FROM ChoixOrientation WHERE anneeuniv = '".$annee."' GROUP BY choix5";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt = $stmt->execute();
        return  $stmt->fetchAll();

    }

    public function getchoixFiliere_50($annee) {

        $query="SELECT '1' as num, choix1 as choix, count(choix1) as c FROM (SELECT codeEtudiant, choix1 FROM ChoixOrientation WHERE anneeuniv = '".$annee."' and codeEtudiant IN (SELECT codetudiant FROM etat WHERE M_CAL > (SELECT AVG(M_CAL) FROM etat))) t GROUP BY choix1
            UNION
            SELECT '2' as num, choix2 as choix, count(choix2) as c FROM (SELECT codeEtudiant, choix2 FROM ChoixOrientation WHERE anneeuniv = '".$annee."' and codeEtudiant IN (SELECT codetudiant FROM etat WHERE M_CAL > (SELECT AVG(M_CAL) FROM etat))) t GROUP BY choix2
            UNION
            SELECT '3' as num, choix3 as choix, count(choix3) as c FROM (SELECT codeEtudiant, choix3 FROM ChoixOrientation WHERE anneeuniv = '".$annee."' and codeEtudiant IN (SELECT codetudiant FROM etat WHERE M_CAL > (SELECT AVG(M_CAL) FROM etat))) t GROUP BY choix3
            UNION
            SELECT '4' as num, choix4 as choix, count(choix4) as c FROM (SELECT codeEtudiant, choix4 FROM ChoixOrientation WHERE anneeuniv = '".$annee."' and codeEtudiant IN (SELECT codetudiant FROM etat WHERE M_CAL > (SELECT AVG(M_CAL) FROM etat))) t GROUP BY choix4
            UNION
            SELECT '5' as num, choix5 as choix, count(choix5) as c FROM (SELECT codeEtudiant, choix5 FROM ChoixOrientation WHERE anneeuniv = '".$annee."' and codeEtudiant IN (SELECT codetudiant FROM etat WHERE M_CAL > (SELECT AVG(M_CAL) FROM etat))) t GROUP BY choix5";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt = $stmt->execute();
        return  $stmt->fetchAll();

    }

    public function getPremierchoixAffecter($annee) {

        $query="SELECT choix1 as choix, count(choix1) as c FROM ChoixOrientation WHERE anneeuniv = '".$annee."' GROUP BY choix1";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt = $stmt->execute();
        return  $stmt->fetchAll();

    }

    
    
    
}
