<?php

namespace App\Repository\Edt;

use Doctrine\ORM\Tools\Pagination\Paginator;
use App\Entity\Edt\Enseignements;
/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementsRepository extends \Doctrine\ORM\EntityRepository
{
	

    public function nomGroupe() {

        $query="SELECT DISTINCT rg.nom FROM ressources_groupes rg, seances_groupes sg, seances s,enseignements e WHERE s.codeSeance = sg.codeSeance
        AND sg.codeRessource = rg.codeGroupe
        AND e.codeEnseignement = s.codeEnseignement
        AND e.codeTypeActivite BETWEEN 1 AND 3 ORDER BY rg.nom ";

        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt = $stmt->execute();
        return  $stmt->fetchAll();

    }

    public function planning_emploi($debut,$fin) {

        $query="SELECT e.nom as 'Exam', rg.nom as 'Groupe', CONCAT(rp.nom, ' ', rp.prenom) as 'Enseignant' , DATE_FORMAT(s.dateSeance , '%W : %d/%m/%Y ') as 'Date', s.heureSeance as 'Heure', rs.nom, ta.alias 
        FROM enseignements e, seances s, ressources_groupes rg, ressources_profs rp,seances_groupes sg, seances_profs sp,seances_salles ss, ressources_salles rs ,types_activites ta
        WHERE e.codeEnseignement = s.codeEnseignement 
            AND s.codeSeance = sg.codeSeance 
            AND s.codeSeance = sp.codeSeance 
            AND s.codeSeance = ss.codeSeance 
            AND sp.codeRessource = rp.codeProf 
            AND sg.codeRessource = rg.codeGroupe 
            AND ss.codeRessource = rs.codeSalle 
            AND e.codeTypeActivite = ta.codeTypeActivite
            AND s.dateSeance BETWEEN '".$debut."' AND '".$fin."'  AND sg.deleted = 0 AND sp.deleted = 0 AND ss.deleted = 0 ORDER BY rg.nom";

        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt = $stmt->execute();
        return  $stmt->fetchAll();

    }


    
}

